development:
  adapter: solid_cable
  silence_polling: true

test:
  adapter: test

production:
  adapter: solid_cable
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: draft_harmony_production
